apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.load_test.namespace }}
  labels:
    releases: {{ .Release.Name }}
data:
  {{- (.Files.Glob "jmeter-scripts/*").AsConfig | nindent 2 }}